Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src = []
group = []

if GetDepend(['AIC_SDIO_MGR_TEST']):
    src += Glob('./test_sdiomgr.c')

group = DefineGroup('sdiomgr-test', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
