
/*
 * Copyright (c) 2025-2026, ArtInChip Technology Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date              Notes
 * 2025-12-30        the first version
 */
#include <rtthread.h>
#include <rtdevice.h>
#include <string.h>
#include "aic_hal_gpio.h"
#include "jy6311_user_cfg.h"
#include "aic_common.h"
#include "codec.h"
#include "jy6311.h"

/**
  * @brief JY6311 I2C Address
  */
#define JY6311_I2C_ADDR     (JY6311_I2C_ADDR_0)

#define ARG_UNUSED(x)   ((void)x)

static JY6311_I2SCfgTypeDef g_jy6311_i2s_cfg = {0};
static JY6311_SysclkCfgTypeDef g_jy6311_sysclk_cfg = {0};

/**
  * @brief JY6311 DAC EQ Coefficient array
  * @note  This parameter array is generated by JY6311 AEtool
  */
static const int32_t dac_eq_filt_coef[] = {
    0xfece5,  0xe02635, 0xfece5, 0xe0264c, 0xfd9e1,
    0x10a9fc, 0xe0aca1, 0xeb35e, 0xe0aca1, 0xf5d5b,
    0xc638b,  0xef09f8, 0x79ca0, 0xef09f8, 0x4002c,
};

/**
  * @brief JY6311 DAC DRC Coefficient array
  * @note  This parameter array is generated by JY6311 AEtool
  */
static const int32_t dac_drc_filt_coef[] = {
    0x76, 0x27, 0x0,  0x12,
    0x11, 0x26, 0x74, 0x7a,
};

/**
  * @brief JY6311 ADC EQ Coefficient array
  * @note  This parameter array is generated by JY6311 AEtool
  */
static const int32_t adc_eq_filt_coef[] = {
    0xd0307, 0xe5f9f1, 0xd0307, 0xe687af, 0xa93cc,
};

/**
  * @brief JY6311 ADC DRC Coefficient array
  * @note  This parameter array is generated by JY6311 AEtool
  */
static const int32_t adc_drc_filt_coef[] = {
    0x76, 0x27, 0x0,  0x12,
    0x11, 0x26, 0x74, 0x7a,
};

/**
  * @brief jy6311 play example
  * @note  1. This example merely demonstrates the interface invocation process. All parameters can be configured by the user.
  *        2. When use multichips, all interfaces change to multichips version, and call jy6311_multichips_i2s_ext_cfg interface
  *            to config I2S extend after i2s config interface.
  */
void jy6311_example_play()
{
    JY6311_I2SCfgTypeDef i2s_cfg;
    JY6311_SysclkCfgTypeDef sysclk_cfg;

    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    memset((void *)&i2s_cfg, 0x0, sizeof(i2s_cfg));
    memset((void *)&sysclk_cfg, 0x0, sizeof(sysclk_cfg));

    /************************** Play Before ***************************/
    // JY6311 Init
    jy6311_init(JY6311_I2C_ADDR, JY6311_INIT_MOD_DAC);

    // JY6311 I2S Config
    i2s_cfg.bclk_invert = g_jy6311_i2s_cfg.bclk_invert;;
    i2s_cfg.lrck_invert = g_jy6311_i2s_cfg.lrck_invert;
    i2s_cfg.fmt = g_jy6311_i2s_cfg.fmt;
    i2s_cfg.role = JY6311_I2S_ROLE_SLAVE;
    i2s_cfg.word_len = g_jy6311_i2s_cfg.word_len;
    jy6311_i2s_cfg(JY6311_I2C_ADDR, &i2s_cfg);
    // Call jy6311_multichips_i2s_ext_cfg if use multichips.

    // JY6311 SYSCLK Config
    sysclk_cfg.extclk_freq = g_jy6311_sysclk_cfg.play_smp_rate * 256;
    sysclk_cfg.extclk_src = JY6311_EXT_CLK_SRC_MCLK;
    sysclk_cfg.play_smp_rate = g_jy6311_sysclk_cfg.play_smp_rate;
    sysclk_cfg.rec_smp_rate = g_jy6311_sysclk_cfg.rec_smp_rate;
    sysclk_cfg.work_mode = JY6311_ADDA_WORK_MODE_NORMAL;
    sysclk_cfg.i2s_lrck_period = 0;
    jy6311_sysclk_cfg(JY6311_I2C_ADDR, &sysclk_cfg);

    /* [Optional] DAC Optional Configuration, eg Path/Volume/EQ/DRC */
    jy6311_dac_eq_cfg(JY6311_I2C_ADDR, true, dac_eq_filt_coef, JY6311_ARRAY_SIZE(dac_eq_filt_coef));
    jy6311_dac_drc_cfg(JY6311_I2C_ADDR, true, dac_drc_filt_coef, JY6311_ARRAY_SIZE(dac_drc_filt_coef));
    jy6311_play_path_cfg(JY6311_I2C_ADDR, JY6311_DAC_OUT_PATH_HEADPHONE);

    // JY6311 Play Start
    jy6311_play_start(JY6311_I2C_ADDR);
}


/**
  * @brief jy6311 record example
  * @note  1. This example merely demonstrates the interface invocation process. All parameters can be configured by the user.
  *        2. When use multichips, all interfaces change to multichips version, and call jy6311_multichips_i2s_ext_cfg interface
  *            to config I2S extend after i2s config interface.
  */
void jy6311_example_record()
{
    JY6311_I2SCfgTypeDef i2s_cfg;
    JY6311_SysclkCfgTypeDef sysclk_cfg;

    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    memset((void *)&i2s_cfg, 0x0, sizeof(i2s_cfg));
    memset((void *)&sysclk_cfg, 0x0, sizeof(sysclk_cfg));

    /*********************** Record Before ****************************/
    // JY6311 Init
    jy6311_init(JY6311_I2C_ADDR, JY6311_INIT_MOD_ADC);

    // JY6311 I2S Config
    i2s_cfg.bclk_invert = g_jy6311_i2s_cfg.bclk_invert;
    i2s_cfg.lrck_invert = g_jy6311_i2s_cfg.lrck_invert;
    i2s_cfg.fmt = g_jy6311_i2s_cfg.fmt;
    i2s_cfg.role = JY6311_I2S_ROLE_SLAVE;
    i2s_cfg.word_len = g_jy6311_i2s_cfg.word_len;
    jy6311_i2s_cfg(JY6311_I2C_ADDR, &i2s_cfg);
    // Call jy6311_multichips_i2s_ext_cfg if use multichips.

    // JY6311 SYSCLK Config
    sysclk_cfg.extclk_freq = g_jy6311_sysclk_cfg.rec_smp_rate * 256;
    sysclk_cfg.extclk_src = JY6311_EXT_CLK_SRC_MCLK;
    sysclk_cfg.play_smp_rate = g_jy6311_sysclk_cfg.play_smp_rate;
    sysclk_cfg.rec_smp_rate = g_jy6311_sysclk_cfg.rec_smp_rate;
    sysclk_cfg.work_mode = JY6311_ADDA_WORK_MODE_NORMAL;
    sysclk_cfg.i2s_lrck_period = 0;
    jy6311_sysclk_cfg(JY6311_I2C_ADDR, &sysclk_cfg);

    /* [Optional] ADC Optional Configuration, eg Gain/EQ/DRC */
    jy6311_record_gain_cfg(JY6311_I2C_ADDR, JY6311_ADC_PGA_GAIN_36dB);      // ADC PGA Gain 36dB
    jy6311_adc_eq_cfg(JY6311_I2C_ADDR, true, adc_eq_filt_coef, JY6311_ARRAY_SIZE(adc_eq_filt_coef));
    jy6311_adc_drc_cfg(JY6311_I2C_ADDR, true, adc_drc_filt_coef, JY6311_ARRAY_SIZE(adc_drc_filt_coef));
#if 0
    /* [Optional] ADC Optional PDM Interface config if use  */
    JY6311_PDMCfgTypeDef pdm_cfg;
    memset((void *)&pdm_cfg, 0, sizeof(pdm_cfg));
    pdm_cfg.timing_invert = false;
    pdm_cfg.clk_io = JY6311_PDMCLK_IO_DEV_ID;
    jy6311_pdm_cfg(JY6311_I2C_ADDR, true, &pdm_cfg);
#endif

    // JY6311 Record Start
    jy6311_record_start(JY6311_I2C_ADDR);

#if 0
    /* [Optional] ADC Optional PDM Interface config if use */
    jy6311_pdm_cfg(JY6311_I2C_ADDR, false, NULL);
#endif
}

void jy6311_drv_set_voice_mute(uint8_t enable)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);
    /* Set volume to mute */
    jy6311_play_vol_cfg(JY6311_I2C_ADDR, 0x00);
    jy6311_record_vol_cfg(JY6311_I2C_ADDR, 0x00);
}

int jy6311_drv_init(struct codec *codec)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    return RT_EOK;
}

int jy6311_drv_start(struct codec *codec, i2s_stream_t stream)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    ARG_UNUSED(codec);

    if (!stream)
        jy6311_example_play();
    else
        jy6311_example_record();
    return 0;
}

int jy6311_drv_stop(struct codec *codec, i2s_stream_t stream)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    if (!stream) {
        // JY6311 Play Stop
        jy6311_play_stop(JY6311_I2C_ADDR);
        /* [Optional] DAC Optional Configuration, eg Volume/EQ/DRC */
        jy6311_play_vol_cfg(JY6311_I2C_ADDR, 0xBF);                      // DAC Digital Volume 0dB
        jy6311_dac_eq_cfg(JY6311_I2C_ADDR, false, NULL, 0);
        jy6311_dac_drc_cfg(JY6311_I2C_ADDR, false, NULL, 0);
        //JY6311 DeInit
        jy6311_deinit(JY6311_I2C_ADDR, JY6311_INIT_MOD_DAC);
    } else {
        // JY6311 Record Stop
        jy6311_record_stop(JY6311_I2C_ADDR);
        /* [Optional] ADC Optional Configuration, eg Gain/EQ/DRC */
        jy6311_record_gain_cfg(JY6311_I2C_ADDR, JY6311_ADC_PGA_GAIN_0dB);// ADC PGA Gain 0dB
        jy6311_adc_eq_cfg(JY6311_I2C_ADDR, false, NULL, 0);
        jy6311_adc_drc_cfg(JY6311_I2C_ADDR, false, NULL, 0);
        // JY6311 DeInit
        jy6311_deinit(JY6311_I2C_ADDR, JY6311_INIT_MOD_ADC);
    }

    return 0;
}

int jy6311_drv_set_protocol(struct codec *codec, i2s_format_t *format)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    switch (format->protocol)
    {
    case I2S_PCM_LONG:
        g_jy6311_i2s_cfg.fmt = JY6311_I2S_FMT_PCM_A;
        break;
    case I2S_PCM_SHORT:
        g_jy6311_i2s_cfg.fmt = JY6311_I2S_FMT_PCM_B;
        break;
    case I2S_PROTOCOL_LEFT_J:
        g_jy6311_i2s_cfg.fmt = JY6311_I2S_FMT_LEFT_J;
        break;
    case I2S_PROTOCOL_I2S:
    default:
        g_jy6311_i2s_cfg.fmt = JY6311_I2S_FMT_I2S;
        break;
    }

    return 0;
}

int jy6311_drv_set_polarity(struct codec *codec, i2s_format_t *format)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    switch (format->polarity)
    {
    case I2S_LEFT_POLARITY_HIGH:
        g_jy6311_i2s_cfg.lrck_invert = true;
        g_jy6311_i2s_cfg.bclk_invert = true;
        break;
    case I2S_LEFT_POLARITY_LOW:
    default:
        g_jy6311_i2s_cfg.lrck_invert = false;
        g_jy6311_i2s_cfg.bclk_invert = false;
        break;
    }

    return 0;
}

int jy6311_drv_set_sample_width(struct codec *codec, i2s_format_t *format)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    switch (format->width)
    {
    case I2S_SAMPLE_WIDTH_20BIT:
        g_jy6311_i2s_cfg.word_len = JY6311_I2S_WORD_LEN_20bit;
        break;
    case I2S_SAMPLE_WIDTH_24BIT:
        g_jy6311_i2s_cfg.word_len = JY6311_I2S_WORD_LEN_24bit;
        break;
    case I2S_SAMPLE_WIDTH_32BIT:
        g_jy6311_i2s_cfg.word_len = JY6311_I2S_WORD_LEN_32bit;
        break;
    case I2S_SAMPLE_WIDTH_16BIT:
    default:
        g_jy6311_i2s_cfg.word_len = JY6311_I2S_WORD_LEN_16bit;
        break;
    }

    return 0;
}

int jy6311_drv_set_sample_rate(struct codec *codec, i2s_format_t *format)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    switch (format->rate)
    {
    case I2S_SAMPLE_RATE_8000:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_8K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_8K;
        break;
    case I2S_SAMPLE_RATE_16000:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_16K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_16K;
        break;
    case I2S_SAMPLE_RATE_32000:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_32K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_32K;
        break;
    case I2S_SAMPLE_RATE_12000:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_12K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_12K;
        break;
    case I2S_SAMPLE_RATE_24000:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_24K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_24K;
        break;
    case I2S_SAMPLE_RATE_96000:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_96K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_96K;
        break;
    case I2S_SAMPLE_RATE_192000:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_192K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_192K;
        break;
    case I2S_SAMPLE_RATE_11025:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_11025;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_11025;
        break;
    case I2S_SAMPLE_RATE_22050:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_22050;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_22050;
        break;
    case I2S_SAMPLE_RATE_44100:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_44100;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_44100;
        break;
    case I2S_SAMPLE_RATE_48000:
    default:
        g_jy6311_sysclk_cfg.play_smp_rate = JY6311_USER_SR_48K;
        g_jy6311_sysclk_cfg.rec_smp_rate = JY6311_USER_SR_48K;
        break;
    }

    return 0;
}

void jy6311_drv_volume_set(struct codec *codec, uint8_t volume)
{
    uint8_t reg_value = 0;

    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    if (volume == 0) {
        // Mute handling
        reg_value = 0x00;  // Mute
    } else if (volume >= 100) {
        // Maximum volume
        reg_value = 0xBF;  // 0dB
    } else {
        // Map 1-100 to 0x01-0xBF (corresponding to -95dB to 0dB)
        // Use linear interpolation: (volume-1) * 190 / 99
        reg_value = 0x01 + (uint8_t)((volume - 1) * 190 / 99);

        // Ensure value is within valid range
        if (reg_value < 0x01) reg_value = 0x01;
        if (reg_value > 0xBF) reg_value = 0xBF;
    }

    /* Set playback and recording volume */
    jy6311_play_vol_cfg(JY6311_I2C_ADDR, reg_value);
    // jy6311_record_vol_cfg(JY6311_I2C_ADDR, reg_value);
}

uint8_t jy6311_drv_volume_get(struct codec *codec)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    uint8_t current_reg_value = 0;
    uint8_t volume = 0;

    // Read current register value from chip
    current_reg_value = jy6311_get_vol_cfg(JY6311_I2C_ADDR);

    if (current_reg_value == 0x00) {
        // Mute state
        volume = 0;
    } else if (current_reg_value >= 0xBF) {
        // Maximum volume
        volume = 100;
    } else {
        // Reverse calculation: map register value back to 1-100 range
        // Original formula: reg_value = 0x01 + (volume - 1) * 190 / 99
        // Reverse: volume = (reg_value - 0x01) * 99 / 190 + 1
        volume = (uint8_t)(((current_reg_value - 0x01) * 99) / 190) + 1;

        // Ensure volume is within valid range
        if (volume > 100) volume = 100;
        if (volume < 1) volume = 1;
    }

    return volume;
}



void jy6311_drv_pa_power(struct codec *codec, uint8_t enable)
{
    uint32_t power_pin = 0;

    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    power_pin = rt_pin_get(AIC_I2S_CODEC_PA_PIN);
    rt_pin_mode(power_pin, PIN_MODE_OUTPUT);

    if (enable)
        rt_pin_write(power_pin, PIN_HIGH);
    else
        rt_pin_write(power_pin, PIN_LOW);
}

void jy6311_drv_dump_reg(struct codec *codec)
{
    uint8_t value;
    int i;

    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    for (i = 0; i < 0x85; i++) {
        value = jy6311_i2c_read_byte(JY6311_I2C_ADDR, i);

        if (i % 16 == 0)
            rt_kprintf("0x%02x: ", i);

        rt_kprintf("0x%02x   ", value);

        if ((i + 1) % 16 == 0)
            rt_kprintf("\n");
    }

    rt_kprintf("\n");
}

struct codec_ops jy6311_drv_ops =
{
    .init = jy6311_drv_init,
    .start = jy6311_drv_start,
    .stop = jy6311_drv_stop,
    .set_protocol = jy6311_drv_set_protocol,
    .set_polarity = jy6311_drv_set_polarity,
    .set_channel = NULL,
    .set_sample_width = jy6311_drv_set_sample_width,
    .set_sample_rate = jy6311_drv_set_sample_rate,
    .set_sclk = NULL,
    .set_mclk = NULL,
    .set_volume = jy6311_drv_volume_set,
    .get_volume = jy6311_drv_volume_get,
    .pa_power = jy6311_drv_pa_power,
    .dump_reg = jy6311_drv_dump_reg,
};

static struct codec jy6311_drv =
{
    .name = "jy6311",
    .ops = &jy6311_drv_ops,
};

int rt_hw_jy6311_init(void)
{
    JY6311_LOG_I("--->%s\n", __FUNCTION__);

    jy6311_i2c_get_client();
    codec_register(&jy6311_drv);

    jy6311_play_vol_cfg(JY6311_I2C_ADDR, 0xBF);     // DAC Digital Volume 0dB
    jy6311_record_vol_cfg(JY6311_I2C_ADDR, 0xBF);   // ADC Digital Volume 0dB

    return 0;
}
INIT_DEVICE_EXPORT(rt_hw_jy6311_init);
