Import('AIC_ROOT')
Import('PRJ_KERNEL')
from building import *

cwd = GetCurrentDir()
src = []
CPPPATH = []

if GetDepend('AIC_I2S_CODEC_SELECT'):
    CPPPATH.append(cwd)
    src += Glob('*.c')

if GetDepend('AIC_I2S_CODEC_ES8388'):
    CPPPATH.append(cwd + 'es8388/')
    src += Glob('es8388/*.c')

if GetDepend('AIC_I2S_CODEC_TLV320'):
    CPPPATH.append(cwd + 'tlv320aic3101/')
    src += Glob('tlv320aic3101/*.c')

if GetDepend('AIC_I2S_CODEC_CS4344'):
    CPPPATH.append(cwd + 'cs4344/')
    src += Glob('cs4344/*.c')

if GetDepend('AIC_I2S_CODEC_ES8311'):
    CPPPATH.append(cwd + 'es8311/')
    src += Glob('es8311/*.c')

if GetDepend('AIC_I2S_CODEC_JY6311'):
    CPPPATH.append(cwd + 'jy6311/')
    src += Glob('jy6311/*.c')

group = DefineGroup('codec', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
